### ISSUE TITLE
Make link to 'Begin the Software Sustainability Evaluation' more visible

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/website#12]
On https://www.software.ac.uk/online-sustainability-evaluation we have

![screencapture-software-ac-uk-online-sustainability-evaluation-1482232911930](https://cloud.githubusercontent.com/assets/1506457/21348913/3bffbe64-c6a7-11e6-92c6-188e82607d12.png)

Maybe we could use a box to highlight the 'Begin the Software Sustainability Evaluation' link, e.g.

![screencapture-software-ac-uk-online-sustainability-evaluation-with-button](https://cloud.githubusercontent.com/assets/1506457/21348927/4fa67174-c6a7-11e6-8a59-002086d6d454.png)

@SimonHettrick and @selina-aragon I'm assigning this issue to you as an way to ask for comments. :-)

**Comment by selina-aragon** [comment]
@rgaiacs I like this. Would you be able to add it? Can we make the button slightly smaller but keep it centred? :)

**Comment by rgaiacs** [comment]
~~~
<p><a href="http://bit.ly/SoftwareSustainabilityEvaluation" style="display:block;background-color:#c62b33;color:white;text-align: center;text-decoration:none;margin:20px;padding:20px;font-weight:bold;border-radius:5px;">Begin the Software Sustainability Evaluation</a></p>
~~~

will be render as

![screencapture-software-ac-uk-node-preview-28ffa1fe-baa0-4c00-95dc-dd527b8a5648-full-1491571145743](https://cloud.githubusercontent.com/assets/1506457/24801722/47138042-1b9d-11e7-83df-3fa9f6fb224d.png)

@selina-aragon This is OK? If yes, could you copy and paste the code snippet and close this issue?

CSS 😍

**Comment by selina-aragon** [comment]
Button a bit smaller? Maybe two cm on each side? :) It looks really well though!

**Comment by selina-aragon** [comment]
This has been done. Closing.
