### ISSUE TITLE
Website is very hard to use on small screens

### ISSUE THREAD

**Issue by swaldman3** [softwaresaved/website#14]
I'm told on Twitter that there is a plan to move to a responsive website... but since there is no issue for it at the moment, here's one :-)

![screenshot_20170824-072314](https://user-images.githubusercontent.com/2036150/29652441-5ab5370e-889d-11e7-8fcb-13e325f2da53.png)

**Comment by selina-aragon** [comment]
Hi @swaldman3. This should be fixed now. We revamped the website about a year ago and content should be able to be read in small screens. Let us know if that's not the case.
