### ISSUE TITLE
Improve ssi_table HTML style

### ISSUE THREAD

**Issue by steve-crouch** [softwaresaved/website#17]
On the https://www.software.ac.uk/resources/guides/sustainability-and-preservation-framework guide, the table has an overly wide first column. The ssi_table style's column width needs to be improved for a more sensible layout on this page (whilst ensuring the change doesn't negatively affect other pages that use this style).

**Comment by steve-crouch** [comment]
Just updated the table to the new table style, and fixed some minor formatting errors - @selina, ok to close?

**Comment by selina-aragon** [comment]
thank you! Yes. Closing now.
