### ISSUE TITLE
index.php in URLss

### ISSUE THREAD

**Issue by mikej888** [softwaresaved/website#19]
index.php is now appearing in URLs in the web site by default e.g. 

* https://www.software.ac.uk/index.php/data-carpentry
* https://www.software.ac.uk/index.php/blog/2018-05-25-archiving-code-and-software-shared-research-journal-author-and-reuser-perspectives

Removing index.php e.g. https://www.software.ac.uk/blog/2018-05-25-archiving-code-and-software-shared-research-journal-author-and-reuser-perspectives, gives a URL that still works OK.

However, it breaks the "Continue reading" links on blog post entries visible at https://www.software.ac.uk/index.php/blog. Clicking these links gives an error:

> Forbidden
> 
> You don't have permission to access /index.php/index.php/blog/2018-05-25-archiving-code-and-software-shared-research-journal-author-and-reuser-perspectives on this server.

**Comment by steve-crouch** [comment]
This issue has been resolved since the revised website was deployed. Closing.
