### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by marioa** [softwaresaved/website#2]
On the page:

   https://www.software.ac.uk/who-do-we-work

If you click on`CGPack` you get a page not found. It appears that the link is pointing to an external web site/page which no longer exists.

**Comment by selina-aragon** [comment]
@marioa thanks. Looking into it.

**Comment by selina-aragon** [comment]
Fixed it. The link now redirects to http://cgpack.sourceforge.net 

Can we close this issue?

**Comment by marioa** [comment]
Sorry, I thought you had closed it. Closing now. Generally I would close and suggest that the submitter either reopens the issue or submits a new one if the problem persists.
