### ISSUE TITLE
Advisory board member pages are under staff for some reason

### ISSUE THREAD

**Issue by shoaibsufi** [softwaresaved/website#21]
On https://www.software.ac.uk/about/advisory-board

Entries are filed under staff - e.g.:

https://www.software.ac.uk/about/staff/person/catherine-jones

Should be something like:

https://www.software.ac.uk/about/advisory-board/person/catherine-jones

**Comment by selina-aragon** [comment]
@shoaibsufi this has been fixed. Closing issue.
