### ISSUE TITLE
Grant numbers (past and current)

### ISSUE THREAD

**Issue by anenadic** [softwaresaved/website#22]
There is info on grants on "How to cite us": https://www.software.ac.uk/about/how-cite-us, but perhaps this should be replicated under Funders and About us too.

**Comment by marioa** [comment]
Have passed on this query to Gillian Law and will report back to see how she responds. Not clear to me whether this is in her remit.

**Comment by anenadic** [comment]
@marioa - in response to Gillian's email:

On Funders page (https://www.software.ac.uk/about/funders) and possibly also on About page (https://www.software.ac.uk/about), I suggest we put a paragraph titled "Grant information" (perhaps at the bottom) with the following text (or something similar) pending approval from Neil/Simon:

"The Software Sustainability Institute has been supported by the UK Engineering and Physical Sciences Research Council (EPSRC) through grant EP/H043160/1 and EPSRC, BBSRC and ESRC Grant EP/N006410/1 and EPSRC, BBSRC, ESRC, NERC, AHRC, STFC and MRC grant EP/S021779/1."

**Comment by marioa** [comment]
Have passed the clarification on to Gillian.

**Comment by marioa** [comment]
From Gillian:
```
Ah, that all makes sense. Seems fine to me! 
```
Going to run past Neil and Simon just to make sure it's ok.

**Comment by marioa** [comment]
From Gillian:
```
Hi! I've made the change on the About page. Talking to Steve Crouch, it'll take a bit of work for him to
re-design the Funders page if we want this, because of the way it's been set up. He's asked if it's high
priority, medium, or low...

I'm not sure who to ask! I guess you and Aleks - I can go to Neil if need be. What do you think?
```

**Comment by anenadic** [comment]
Thanks to Gillian & @marioa - I think it is good enough to have it at least on the About page if the Funders page is complicated to fiddle with so we can maybe close this issue?
