### ISSUE TITLE
Broken links in site to Oxford papers

### ISSUE THREAD

**Issue by snim2** [softwaresaved/website#23]
On this page:

https://software.ac.uk/resources/get-speed

there are links to:

* http://digital-research-2012.oerc.ox.ac.uk/papers/doing-science-properly-in-the-digital-age/at_download/file
* http://digital-research-2012.oerc.ox.ac.uk/papers/the-research-software-engineer

which are both broken (at least from within `aston.ac.uk`)

**Comment by steve-crouch** [comment]
Thanks for the heads-up! This looks like a site within Oxford's e-Research Centre that is currently down. I've notified them of the outage, and asked if/when they'll fix it.

**Comment by steve-crouch** [comment]
Due to the age of the site, they state there are no plans to fix the site. I've replaced the broken links on the page with ones that work for these publications. @snim2 could you please verify?

**Comment by snim2** [comment]
@steve-crouch that all looks good to me now Steve, thanks for sorting this!

**Comment by snim2** [comment]
I should really have closed this after the last comment!
