### ISSUE TITLE
Link to  A to Z: Editorial Style Guide is broken

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/website#27]
https://www.software.ac.uk/about/brand-guidelines has

> Editorial style guide
>
> Refer to our [A to Z: Editorial Style Guide](https://software.ac.uk/editorial-style-guide) to ensure copy written for the Institute brand is consistent across our online and printed platforms.

https://software.ac.uk/editorial-style-guide?_ga=2.245428420.1717535898.1611729456-725494665.1611729456 returns `
Error: Access Denied` to me. Can I read your editorial style guide? Thanks!

**Comment by selina-aragon** [comment]
Hi @rgaiacs 

Thanks for pointing this out!

We'd unpublished it from the website because we use it internally only. However, I've made it available again, as it's linked to our branding guidelines.
[www.software.ac.uk/editorial-style-guide](www.software.ac.uk/editorial-style-guide)

Hope it helps!

**Comment by rgaiacs** [comment]
@selina-aragon Thanks! It helped.
