### ISSUE TITLE
Providing some form of contact details for SSI staff

### ISSUE THREAD

**Issue by marioa** [softwaresaved/website#3]
When you go to the staff page: https://www.software.ac.uk/people there are no contact details provided for any staff members. Would be good to have some mechanism whether it is done indirectly via `info@software.ac.uk` or a recipe is provided provided, e.g. `first initial.surname@software.ac.uk`.

**Comment by anenadic** [comment]
I agree that we need contact details (at least email addresses) for people, unless they specifically do not want it.

**Comment by SimonHettrick** [comment]
Added a straw poll. People who want their email address on the site can have it. People who don't can choose not to.

**Comment by SimonHettrick** [comment]
Looks like we're going to add a generic thing about "if you want to contact people, use the form initial.surname@software.ac.uk"

Over to you @selina-aragon

**Comment by selina-aragon** [comment]
I've added this sentence in the Contact us and People pages. 

I'm closing this ticket.
