### ISSUE TITLE
Worth publicising this issue tracker to log issues with the website on www.software.ac.uk?

### ISSUE THREAD

**Issue by marioa** [softwaresaved/website#4]
Is it worth publicising this issue tracker in www.software.ac.uk for people to log any issues they might have with web site?

**Comment by selina-aragon** [comment]
I think this is worth doing in a few months from now, once we've sorted out a couple of more things on the website. We get notifications from people on Twitter when something doesn't work anyway.

**Comment by selina-aragon** [comment]
I'm adding this to the super ticket of the website redesign. We'll need to ask people for feedback at some point. https://github.com/softwaresaved/InstituteIssues/issues/142
