### ISSUE TITLE
Missing teaser

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/website#7]
Drupal 8 don't have teaser.

Screenshot from Drupal 6:

![image10](https://cloud.githubusercontent.com/assets/1506457/18130488/332d1a56-6f87-11e6-9022-6dc0e6723f8d.png)

**Comment by iaine** [comment]
If you click the "Edit summary" link when creating the post, the summary box is shown. Drupal 8 hides it by default in the blog post.
