### ISSUE TITLE
Link to fellows contributions are broken

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/website#8]
On Drupal 6: https://www.software.ac.uk/search/node/Alexander%20Konovalov

On Drupal 8 we need to use https://www.software.ac.uk/search/node?keys=Alexander+Konovalov

**Comment by rgaiacs** [comment]
I will replace the links with https://www.software.ac.uk/author/alexander-konovalov in the upcoming weeks.

**Comment by iaine** [comment]
This is part of the search discussion and exploration.

**Comment by iaine** [comment]
Please use the correct taxonomy as well, otherwise this might undo some of the work that has taken place.

**Comment by olexandr-konovalov** [comment]
Thanks @rgaiacs! Also, the new search is incomplete. I think before I was able to see more search results. One of the missing pages, for example, is https://www.software.ac.uk/gap-days-workshop-2014 which is searchable via "GAP Days" but not by my name.

**Comment by rgaiacs** [comment]
@alex-konovalov I will add the correct metadata on the posts to improve the search but since this need to be done manually will take a few days pass over all the posts. Sorry.

**Comment by olexandr-konovalov** [comment]
@rgaiacs thanks. Someone reported this to me in a particular context of looking at Fellow profiles to see what they have been doing after becoming Fellows, so it may be helpful if one could manage to fix this before the application deadline...

**Comment by rgaiacs** [comment]
I replaced all the link to https://www.software.ac.uk/author/firstname-lastname. Still need to add the relevant metadata on blog posts but will close this.
