### ISSUE TITLE
"See more from these authors" Box

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/website#9]
On Drupal 6 we could use `author:Full Name"` as tag and get the "See more from these authors" box.

![screencapture-ssi-www-epcc-ed-ac-uk-blog-2016-07-20-protoms-passes-test-developing-test-suite-biomolecular-simulation-software-1473435465683](https://cloud.githubusercontent.com/assets/1506457/18393125/2c43fd28-76ac-11e6-9c74-c1fe713d53f6.png)

The tags and the box were dropped in Drupal 8.

![screencapture-software-ac-uk-blog-2016-08-17-protoms-passes-test-developing-test-suite-biomolecular-simulation-software-1473435490762](https://cloud.githubusercontent.com/assets/1506457/18393157/46d36412-76ac-11e6-8c97-50d5fe37b3ba.png)

**Comment by iaine** [comment]
The tags have not been dropped but are in the process of being updated. A lot of the work has been done but an update needs to take place to complete it.

**Comment by rgaiacs** [comment]
This is still the case.

![screencapture-software-ac-uk-blog-2016-09-09-protoms-passes-test-developing-test-suite-biomolecular-simulation-software-2018-03-12-10_30_18](https://user-images.githubusercontent.com/1506457/37278686-6f58b524-25e0-11e8-8fa0-1bb059f2fe99.png)

@selina-aragon Do we have some like this in the new layout?

**Comment by rgaiacs** [comment]
Resolved on the new website.

![screencapture-software-ac-uk-blog-2016-07-20-protoms-passes-test-developing-test-suite-biomolecular-simulation-software-2018-07-16-10_28_08](https://user-images.githubusercontent.com/1506457/42751528-f8ddd1fc-88e2-11e8-99d4-14553e13ddea.png)
